name: Generate 3D contribution graph

on:
  schedule:
    - cron: '17 7 * * *'
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/profile-3d.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      # v0.9.2
      - uses: yoshi389111/github-profile-3d-contrib@5b718734e8da645411919f0ae9ab9e7f9377158f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit graph
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -- profile-3d-contrib/profile-gitblock.svg
          if ! git diff --cached --quiet; then
            git commit -m 'Update 3D contribution graph'
            git push
          fi
